---
apiVersion: v1
kind: Pod
metadata:
  name: kube-agent-default
  namespace: jenkins
spec:
  containers:
    - name: docker
      image: docker:20.10.12-alpine3.15
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
    - name: maven
      image: maven:3.8.4-jdk-11
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2/repository
    - name: argo-rollouts
      image: quay.io/argoproj/kubectl-argo-rollouts:master
      command:
        - cat
      tty: true
      securityContext:
        fsGroup: 0
        runAsUser: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                  - docker-desktop
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-pvc