---
apiVersion: v1
kind: Service
metadata:
  name: userservice-demo-preview
  namespace: default
spec:
  type: NodePort
  selector:
    app: userservice-demo-rollout
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: userservice-demo-active
  namespace: default
spec:
  type: NodePort
  selector:
    app: userservice-demo-rollout
  ports:
    - port: 80
      targetPort: 8080
