server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.demo.backend: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.kafka: TRACE
    org.apache.kafka: INFO
    org.hibernate: INFO
  file:
    name: "target/backend.log"
  logback:
    rollingpolicy:
      max-history: 7

spring:
  application:
    name: backend
  jackson:
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion:
      - always
      - non_null
      - non_absent
      - non_default
      - non_empty
  datasource:
    # url: "jdbc:h2:file:/tmp/data/demo"
    # url: "jdbc:h2:tcp://localhost/~/demo"
    # url: "jdbc:h2:file:~/demo;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
    url: "jdbc:h2:mem:demo"
    driver-class-name: "org.h2.Driver"
    username: sa
    hikari:
      auto-commit: false
      connection-init-sql: "select 1"
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  sql:
    init:
      mode: always
      schema-locations: "classpath:sql/schema.sql"
      data-locations: "classpath:sql/data.sql"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

---
spring:
  config:
    activate:
      on-profile: dev
#  spring.jackson.default-property-inclusion=always, non_null, non_absent, non_default, non_empty
