server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    example.demo.backend: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.kafka: TRACE
    org.apache.kafka: INFO
    org.hibernate: INFO
  file:
    name: "target/backend.log"
  logback:
    rollingpolicy:
      max-history: 7

spring:
  application:
    name: userservice
  jackson:
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion:
      - always
      - non_null
      - non_absent
      - non_default
      - non_empty
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:53306/SAMPLE?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: scott
    password: tiger123$
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: "classpath:sql/schema-mysql.sql"
      data-locations: "classpath:sql/data.sql"
  jpa:
    database: mysql
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"

---
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:53306/SAMPLE?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: scott
    password: tiger123$
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: "classpath:sql/schema-mysql.sql"
      data-locations: "classpath:sql/data.sql"
  jpa:
    database: mysql
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
