---
version: "3"

# docker network create runtime-external
# docker network ls
networks:
  default:
    external:
      name: runtime-external

services:
  userservice:
    image: userservice-demo:1.0.0
    container_name: userservice
    restart: always
    ports:
      - 80:8080
    environment:
      - SPRING_PROFILE=prd
#    networks:
#      - runtime-external

# docker-compose up userservice
#  curl -v http://localhost:8080/api/users/query
