version: '3.1'

networks:
  runtime-net:
    external: false

services:
  mysql:
    restart: always
    image: mysql:5.7.37
    container_name: mysql
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_ROOT_PASSWORD=root123$
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - /tmp/data/mysql:/var/lib/mysql
    ports:
      - 53306:3306
    # user: root
    networks:
      - runtime-net