---
apiVersion: v1
kind: Pod
metadata:
  name: dx-docker-agent
  namespace: default
spec:
  containers:
    - name: docker
      image: "docker:20.10.12-alpine3.15"
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
