---
apiVersion: v1
kind: Pod
metadata:
  name: dx-maven-agent
  namespace: jenkins
spec:
  containers:
    - name: maven
      image: maven:3.8.4-jdk-11
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      resources:
        limits:
          memory: "2Gi"
          cpu: "4000m"
        requests:
          memory: "1Gi"
          cpu: "2000m"
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2/repository
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "kubernetes.io/os"
                operator: In
                values:
                  - linux
  volumes:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-pvc